org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.newDsl=false
android.builtInKotlin=false
kotlin.incremental=false
kotlin.incremental.multiplatform=false
kotlin.caching.enabled=false
